#!/bin/bash
# Author: Dimitri Tarasowski
# Date created: 02/21/2019
# Desc: This script creates a package.json with predefined serverless settings
# Date modified: 02/21/2019

if [ ${1} == serverless ]
  then
    echo
    echo 'package.json creation has been started...'

echo
echo What is your project name?
read project
project="$(tr [A-Z] [a-z] <<< "$project" | sed "s/ /-/g")" 
echo
echo What is your project about?
read description
echo
echo What is your stack name?
read stack
stack="$(tr [A-Z] [a-z] <<< "$stack" | sed "s/ /-/g")" 
echo
echo What is your s3 bucket name for this project?
read s3bucket
s3bucket="$(tr [A-Z] [a-z] <<< "$s3bucket" | sed "s/ /-/g")" 
echo
echo What is the name of your SAM template?
read template
template="$(tr [A-Z] [a-z] <<< "$template" | sed "s/ /-/g")" 
echo
if [ $template != *.yaml ]
  then template="$template".yaml
fi
echo In which region are you going to depoy the stack?
select reg in eu-central-1 eu-west-1 us-east-1;
do
  case $reg in
    "eu-central-1")
    region=$reg
    break
    ;;
    "eu-west-1")
    region=$reg
    break
    ;;
    "us-east-1")
    region=$reg
    break
    ;;
    *) 
    echo 'Invalid option';;
  esac
done
echo
echo 'Your package.json file has been created...'
echo

DIR=`pwd`
package='
{
  "name":'"\"$project\""',
  "version": "1.0.0",
  "description": '"\"$description\""',
  "main": "index.js",
  "scripts": {
    "folder": "rm -rf build && mkdir build",
    "bucket": "aws s3api create-bucket --bucket '$s3bucket' --region '$region' --create-bucket-configuration LocationConstraint='$region'",
    "package": "aws cloudformation package --template-file '$template' --output-template-file build/output.yaml --s3-bucket '$s3bucket'",
    "deploy": "aws cloudformation deploy --template-file build/output.yaml --stack-name '$stack'  --capabilities CAPABILITY_NAMED_IAM",
    "qd": "npm run folder && npm run package && npm run deploy"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}'

echo $package > "$DIR/package.json"
fi  

if [ $1 == pipeline ]
  then 
    echo "Pipeline file creation has beend started..."
  else
    echo Please provide something as the first argument such as [serverless, pipeline]
fi
